export const ROUTES = {
  CANDIDATE: {
    DASHBOARD: "/dashboard",
    BROWSE_JOBS: "/jobs",
    JOB_DETAILS: "/jobs/:id",
    SAVED_JOBS: "/saved-jobs",
    APPLICATIONS: "/applications",
    MESSAGES: "/messages",
    NOTIFICATIONS: "/notifications",
    SETTINGS: "/settings",
    PROFILE: "/profile",
  },
  RECRUITER: {
    DASHBOARD: "/recruiter/dashboard",
    POST_JOB: "/recruiter/post-job",
    MANAGE_JOBS: "/recruiter/manage-jobs",
    JOB_DETAILS: "/recruiter/jobs/:id",
    APPLICANTS: "/recruiter/applicants",
    CANDIDATE_PREVIEW: "/recruiter/applicants/:id",
    COMPANY: "/recruiter/company",
    ANALYTICS: "/recruiter/analytics",
    MESSAGES: "/recruiter/messages",
    NOTIFICATIONS: "/recruiter/notifications",
    SETTINGS: "/recruiter/settings",
    HELP: "/recruiter/help",
    LOGOUT: "/recruiter/logout",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    MANAGE_USERS: "/admin/users",
    MANAGE_JOBS: "/admin/jobs",
    COMPANIES: "/admin/companies",
    SETTINGS: "/admin/settings",
  },
} as const
